creation_rules:
  - path_regex: ^src/terraform/development/.*
    kms: arn:aws:kms:ap-northeast-1:012123456789:key/3f19d006-6c05-4fbf-93fd-b7604c928ad8
    encrypted_regex: ^(.*_password|.*_secret)$

  # sample 
  - path_regex: ^src/terraform/production/.*
    kms: arn:aws:kms:ap-northeast-1:123456789012:key/PROD-KEY-ARN-UUID
    encrypted_regex: ^(.*_password|.*_secret)$
